raw_output = ""
user_token = ""

[filter]
  limit = ""
  offset = ""
  topic = ""

[remotes]
  bootstrap_url = "http://localhost:9013"
  certs_url = "http://localhost:9019"
  http_adapter_url = "http://localhost/http:9016"
  reader_url = "http://localhost:9011"
  things_url = "http://localhost:9000"
  tls_verification = false
  users_url = "http://localhost:9002"
  channels_url = "http://localhost:9005"
